export const unis = [
  "University of Torbat Heydarieh",
  "Sabzevar University of New Technology",
  "University of Applied Science and Technology of Qom",
  "Malayer University",
  "Mazandaran University of Science and Technology",
  "Shariaty Technical College",
  "Jundishapur University of Technology",
  "University of Zabol",
  "Islamic Azad University, Shoushtar Branch",
  "Islamic Azad University, Qom branch",
  "University of Iranians",
  "International University of Chabahar",
  "University of Islamic Republic of Iran Broadcasting",
  "Iranian Center for Translation Studies",
  "Islamic Azad University of Tafresh",
  "Islamic Azad University of Zanjan",
  "Kharazmi University",
  "Khayyam Institute of Higher Education, Mashhad",
  "Islamic Azad University, Sanandaj branch",
  "Payam Noor University of Mahabad",
  "Tabarestan University",
  "Ramin University of Agriculture and Natural Resources",
  "Islamic Azad University of Kerman",
  "Islamic Azad University of Saveh",
  "University of Mazandaran",
  "Malek Ashtar University of Technology",
  "Mofid University",
  "Petroleum University of Technology",
  "Azad University at Qazvin",
  "Qeshm Institute of Higher Education",
  "Semnan University",
  "Shahed University",
  "Shahid Bahonar University of Kerman",
  "Shahid Rajaee Teacher Training University",
  "Shahid Sattari University of Aeronautical Engineering",
  "Shahrekord University",
  "Sharif University of Technology International Campus",
  "Sheikh Bahaei University",
  "Shiraz Pasargad Higher Education Institute",
  "Shiraz University of Technology",
  "Shomal University",
  "Tafresh University",
  "Tarbiat Modares University",
  "University of Birjand",
  "University of Bonab",
  "University of Guilan",
  "University of Mohaghegh Ardabili",
  "University of Religions and Denominations",
  "University of Science and Culture",
  "University of Sistan and Baluchestan",
  "Zand Institute of Higher Education",
  "Allameh Tabataba'i University",
  "University of Yazd",
  "Baqir al-Olum University",
  "Islamic Azad University, Ahvaz",
  "Islamic Azad University, Tunkabon branch",
  "University of Gonabad",
  "Islamic Azad University, Naragh Branch",
  "Farhangian University of Ilam",
  "University of Bojnord",
  "Islamic Azad University of Khorasgan",
  "Ilam University",
  "Kermanshah University of Technology",
  "Islamic Azad University, Semnan Science and Research Unit",
  "University of Judicial Sciences and Administrative Services",
  "Islamic Azad University of Ardabil",
  "Sari Agricultural Sciences and Natural Resources University",
  "Karaj Payame Noor University",
  "Islamic Azad University of Shahrud",
  "Hormozgan University",
  "Farabi University",
  "Kermanshah Technical and Vocational University",
  "Birjand University of Technology",
  "Islamic Azad University, Sarab branch",
  "Islamic Azad University of Arsanjan",
  "Islamic Azad University, Abarkoh branch",
  "University of Islamic Religions",
  "Islamic Azad University gives a unit",
  "Islamic Azad University, Islamshahr branch",
  "Damghan University",
  "Azad University of Iran",
  "Allameh Tabatabaei University (RA)",
  "Al-Mustafa International University",
  "Lorestan University",
  "Sadjad University of Technology",
  "Payame Noor University, Khanj branch",
  "Applied Scientific University of Persepolis",
  "Islamic Azad University of Rudehen",
  "University of Maragheh",
  "Razavi University of Islamic Sciences",
  "Chabahar University of Maritime and Marine Sciences",
  "Golestan University",
  "Islamic Azad University of Saqqez",
  "Islamic Azad University of Borujerd",
  "Islamic Azad University of Varamin-Pishva",
  "Islamic Azad University of Semnan",
  "Islamic Azad University, Aligudarz branch",
  "Yasuj University",
  "University of Social Welfare and Rehabilitation Sciences",
  "Islamic Azad University of Hamadan",
  "University of Environment",
  "Imam Reza International University",
  "Iran University of Science and Technology, Arak branch",
  "Applied Scientific University of Karaj Municipality",
  "Islamic Azad University of Dezful",
  "Islamic Azad University, Khorramabad branch",
  "Islamic Azad University of Astara",
  "Islamic Azad University of Amol",
  "Islamic Azad University, Marvdasht",
  "Sirjan University of Technology",
  "Islamic Azad University of Sari",
  "University of Economic Sciences",
  "Iranian Research Institute of Philosophy",
  "Payam Noor University of Shiraz",
  "Islamic Azad University, Gonabad branch",
  "Institute for Humanities and Cultural Studies",
  "National University of Iran",
  "Urmia University of Technology",
  "Islamic Azad University, Takestan branch",
  "University of Kashan",
  "Isfahan University of Technology",
  "Islamic Azad University Dental Branch of Tehran",
  "Islamic Azad University, Fars Science and Research Branch",
  "Islamic Azad University of Anar",
  "Islamic Azad University North Tehran Branch",
  "Islamic Azad University of Ahar",
  "Islamic Azad University, South Tehran Branch",
  "Islamic Azad University of Arak",
  "Islamic Azad University of Anzali",
  "Islamic Azad University of Bojnord",
  "Islamic Azad University of Garmsar",
  "Islamic Azad University of Gorgan",
  "Islamic Azad University of Karaj",
  "Islamic Azad University of Kermanshah",
  "Islamic Azad University of Khomeynishahr",
  "Islamic Azad University of Majlesi",
  "Islamic Azad University of Mashhad",
  "Islamic Azad University of Malard",
  "Islamic Azad University of Rasht",
  "Islamic Azad University of Parand",
  "Islamic Azad University of Ray",
  "Islamic Azad University of Shiraz",
  "Jami Institute of Technology",
  "Islamic Azad University, Buin-Zahra",
  "Khuzestan Institute of Higher Education",
  "Islamic Azad University Yasuj",
  "Urmia University",
  "College of Agriculture",
  "Q28936333",
  "Hakim Sabzevari University",
  "Imam Khomeini International University",
  "Islamic Azad University of Birjand",
  "Tabriz Art University",
  "Shahid Chamran University of Ahvaz",
  "Islamic Azad University of Farahan",
  "University of Arak",
  "Islamic Azad University, Babol branch",
  "Razi University",
  "Islamic Azad University of Nishapur",
  "BahÃ¡'Ã­ Institute for Higher Education",
  "Tabriz University of Technology",
  "University of Zanjan",
  "Islamic Azad University of Lahijan",
  "University of Neyshabur",
  "Iran University of Science and Technology",
  "Persian Gulf University",
  "University of Qom",
  "Power and Water University of Technology",
  "Shamsipour Technical College",
  "Research Institute of Petroleum Industry",
  "Allameh Mohaddes Noori University",
  "Arak University of Technology",
  "Azarbaijan Shahid Madani University",
  "Besat Institute of Higher Education of Kerman",
  "University College of Azarabadegan",
  "Bu-Ali Sina University",
  "Faculty of Engineering - Kharazmi University",
  "Amol University",
  "Babylon University",
  "Behshahr University",
  "College of Agriculture in Gonbad",
  "Islamic Azad University Science and Research Branch",
  "Faculty of Agriculture of Islamic azad university Science and Research branch",
  "Faculty of Agriculture of Islamic Azad university Roudehen Branch",
  "Islamic Azad University of Falavarjan",
  "Golpayegan University of Engineering",
  "Gorgan University",
  "Department of civil engineering of Semnan university",
  "Amirkabir University of Technology, Mahshahr branch",
  "Amirkabir University of Technology, Bandar Abbas branch",
  "Islamic Azad University, Torbat Jam branch",
  "Islamic Azad University Kurdistan Province",
  "Jundi-shapur University of Technology",
  "Yasouj University",
  "Shahid Motahari University",
  "Islamic Azad University, Miyaneh Branch",
  "Daneshgahe majlesi",
  "Daneshgah e Azade Mobarakeh",
  "sepehr art university",
  "Gonbad-e Kavus University",
  "Islamic Azad University of Tonekabon",
  "Islamic Azad University Of Urmia",
  "Islamic Azad University of Yazd",
  "Islamic Azad University of Takestan",
  "Islamic Azad University of Qaem Shahr",
  "Islamic Azad University of Fasa",
  "Islamic Azad University of Bandar Abbas",
  "Islamic Azad University of Dehaghan",
  "Islamic Azad University of Kazerun",
  "Islamic Azad University of Jenah",
  "Islamic Azad University of Mobarakeh",
  "Islamic Azad University of Bostanabad",
  "Islamic Azad University of Meybod",
  "Islamic Azad University of Mehriz",
  "Islamic Azad University of Qom",
  "Islamic Azad University of Quchan",
  "Islamic Azad University of Shirvan",
  "Islamic Azad University of Firuzkuh",
  "Daneshgah e Azade Dehaghan",
  "Fasa University",
  "Islamic Azad University of Khomein",
  "Islamic Azad University of Aliabad Katoul",
  "Islamic Azad University, Marand",
  "Islamic Azad University, Langarud Branch",
  "Faculty of Basic Sciences and Engineering, Bijar",
  "University of Kurdistan",
  "Meybod University",
  "University of Applied Science and Technology of Kazerun",
  "Art University of Isfahan",
  "Islamic Azad University of Najafabad",
  "Payame Noor University",
  "Institute for Advanced Studies in Basic Sciences",
  "Shahid Beheshti Teacher Training College",
  "Dar ul-Funun",
  "Islamic Azad University of Komijan",
  "Islamic Azad University Central Tehran Branch",
  "Islamic Azad University of Sabzevar",
  "Islamic Azad University of Mahabad",
  "Islamic Azad University, Malayer Branch",
  "Islamic Azad University of Kashan",
  "Montazeri Technical University of Mashhad",
  "Qom University of Technology",
  "Shahrud University of Technology",
  "Garmsar University",
  "Institute for Cognitive Science Studies",
  "K. N. Toosi University of Technology",
  "Islamic Azad University, Firdous branch",
  "Farhangian University",
  "Islamic Azad University of Damavand",
  "Persian Gulf International Education Center",
  "Shiraz University of Arts",
  "Quchan University of Advanced Technologies Engineering",
  "Adiban Institute of Higher Education",
  "Damavand College",
  "Kerman Graduate University of Technology",
  "Islamic Azad University of Masjed Soleyman",
  "Islamic Azad University Bushehr Branch",
  "Islamic Azad University of Shahrekord",
  "Amirkabir University of Technology, Garmsar branch",
  "Islamic Azad University, Mahalat branch",
  "Islamic Azad University of Mohajeran",
  "Islamic Azad University, Mazandaran Graduate School of Science and Research",
  "Khayyam University of Mashhad",
  "University of Science and Arts (Yazd)",
  "Mehr Alborz University",
  "Khayyam University of Mashhad",
  "Islamic Azad University, Arak Science and Research Unit",
  "Islamic Azad University, Saveh Science and Research Unit",
  "Dehlran University of Applied Sciences",
  "Isfahan Sepehr College",
  "Najand Institute of Higher Education",
  "Islamic Azad University of Shahinshahr",
  "Jahrom University",
  "Islamic Azad University, Jiroft Branch",
  "Amin Police Academy",
  "Islamic Azad University of Bukan",
  "Islamic Azad University, Shush branch",
  "Islamic Azad University of Mahshahr",
  "Jiroft University",
  "Supreme National Defense University",
  "Amol University of Special Modern Technologies",
  "Islamic Azad University Islamshahr Branch",
  "Islamic Azad University, Khorramabad Branch",
  "Islamic Azad University, Zahedan Branch",
  "Islamic Azad University, Khoy Branch",
  "Islamic Azad University, Larestan Branch",
  "Islamic Azad University, Nowshahr Branch",
  "Islamic Azad University, Sirjan Branch",
  "Abhar Islamic Azad University",
  "Ashtian Islamic Azad University",
  "Islamic Azad University Ahwaz Branch",
  "Islamic Azad University Science and Research Branch Ahwaz",
  "Islamic Azad University Aliabad Katoul Branch",
  "Islamic Azad University Ardestan Branch",
  "Islamic Azad University Babol Branch",
  "Islamic Azad University Bonab Branch",
  "Islamic Azad University of Estahban",
  "Islamic Azad University of Firuzabad",
  "Islamic Azad University of Izeh",
  "Islamic Azad University of Jiroft",
  "Islamic Azad University Kashmar",
  "Bagher Aloloum University",
  "Islamic Azad University Shahre Rey Branch",
  "Shahid Ashrafi Esfahani University",
  "Islamic Azad University of Torbate Heydarieh",
  "University of Tabriz Department of English Language and Literature",
  "Iranian Law and Legal Research Institute",
  "Q110967012",
  "Kashmar Higher Education Center",
  "Payame Noor University of Bahnemir",
  "Islamic Azad University of Kish",
  "Islamic Azad University of Qeshm",
  "Payame Noor University of Bushehr",
  "Islamic Azad University of Natanz",
  "College of Fine Arts",
  "CATC",
  "Faculty of Theology and Islamic Studies of the University of Tehran",
  "Faculty of Art and Architecture, Islamic Azad University, South Tehran Branch",
  "Sharif University of Technology, Department of Electrical Engineering",
  "Shushtar Art Faculty",
  "Faculty of Chemical Engineering, Iran University of Science and Technology",
  "Allameh Tabatabai Management School",
  "Faculty of Science, Khajahansiruddin Tusi University of Technology",
  "Faculty of Architecture, Design and Fine Arts of the American University of Kyrenia",
  "Faculty of Electrical Engineering, Amirkabir University of Technology",
  "Faculty of Geography, University of Tabriz",
  "Faculty of Chemical and Petroleum Engineering, University of Tabriz",
  "Tabriz University Faculty of Economics, Management and Commerce",
  "Technical and engineering faculty of Tabriz University",
  "Faculty of Engineering, Ferdowsi University of Mashhad",
  "Faculty of Social Sciences of the University of Tehran",
  "Faculty of Science, University of Isfahan",
  "Technical and Engineering Faculty of Shahid University",
  "Faculty of Mathematics, University of Tabriz",
  "Shahid Rajaei Lahijan Technical College",
  "Faculty of Petroleum Engineering, Amirkabir University of Technology",
  "Faculty of Management and Accounting, Azad Qazvin University",
  "Faculty of Engineering and Science and Materials of Sharif University of Technology",
  "Faculty of Nuclear Engineering and Physics, Amirkabir University of Technology",
  "Faculty of Chemistry, Sharif University of Technology",
  "Tabriz University Faculty of Literature and Human Sciences",
  "Faculty of Literature and Humanities, Dr. Ali Shariati, Ferdowsi University of Mashhad",
  "Technical Faculty of Tabriz University",
  "Faculty of Civil Engineering and Architecture, Azad Qazvin University",
  "Faculty of Law, Shahid Beheshti University",
  "Faculty of Physics, University of Tabriz",
  "Faculty of Mechanical Engineering, Amir Kabir University of Technology",
  "History of Science Research Institute",
  "Faculty of Civil Engineering, Sharif University of Technology",
  "Faculty of Industrial Engineering, Iran University of Science and Technology",
  "Faculty of Electrical and Computer Engineering and Information Technology of Qazvin Azad University",
  "Technical and Vocational University of Soroush Center, Isfahan",
  "Faculty of Theology and Religions of Shahid Beheshti University",
  "Faculty of Industry and Mechanics, Qazvin Azad University",
  "Central Tehran Islamic Azad University Technical Faculty",
  "Faculty of Social Sciences, Allameh Tabatabai University",
  "Faculty of Computer Engineering and Information Technology, Amirkabir University of Technology",
  "Tabriz University Faculty of Humanities and Social Sciences",
  "Tabriz University Faculty of Theology and Islamic Sciences",
  "Faculty of Architecture and Urban Planning, Iran University of Science and Technology",
  "Faculty of Mathematics, Iran University of Science and Technology",
  "Faculty of Mining Engineering, Metallurgy, Amirkabir University of Technology",
  "Faculty of Earth Sciences, Shahid Beheshti University",
  "Tabriz University Faculty of Natural Sciences",
  "Tabriz University Faculty of Persian Literature and Foreign Languages",
  "Faculty of Mechanical Engineering, University of Tabriz",
  "Faculty of Agriculture, University of Tabriz",
  "Faculty of Architecture and Urban Planning, Shahid Beheshti University",
  "Faculty of Civil Engineering, University of Tabriz",
  "School of Railway Engineering",
  "Faculty of Mechanical Engineering, Khwajahansiruddin Tusi University of Technology",
  "Faculty of Physics, Iran University of Science and Technology",
  "Faculty of Automotive Engineering, Iran University of Science and Technology",
  "Faculty of Chemistry, Iran University of Science and Technology",
  "Faculty of Economic and Political Sciences, Shahid Beheshti University",
  "Faculty of Physical Education and Sports Sciences of Shahid Beheshti University",
  "Faculty of Mechanical Engineering, Sharif University of Technology",
  "Faculty of Cinema and Theater",
  "Tabriz University Faculty of Educational Sciences and Psychology",
  "Faculty of Mechanical Engineering, Iran University of Science and Technology",
  "Faculty of Literature and Humanities, Shahid Beheshti University",
  "Faculty of News",
  "Faculty of Architecture and Art, Islamic Azad University, Tabriz branch",
  "Faculty of Aerospace Engineering, Khwajahansiruddin Tusi University of Technology",
  "Faculty of Management, Economics and Accounting, Islamic Azad University, Tabriz branch",
  "Tehran University technical faculties campus",
  "Faculty of Chemistry, University of Tabriz",
  "Faculty of Entrepreneurship of the University of Tehran",
  "Faculty of Industrial Engineering, Amirkabir University of Technology",
  "Sharif Graduate School of Management and Economics",
  "Faculty of Civil and Environmental Engineering, Amirkabir University of Technology",
  "Faculty of Engineering, Islamic Azad University, South Tehran branch",
  "N.I.O.C. school of Accounting and Finance",
  "Faculty of Persian Language and Literature",
  "Faculty of Mathematical Sciences, Alzahra University",
  "University of Tehran, College of Agriculture & Natural Resources",
  "Faculty of World Studies of the University of Tehran",
  "Faculty of Desert Studies",
  "Faculty of New Sciences and Technologies of the University of Tehran",
  "Mohajer Technical University of Isfahan (MTU)",
  "Department of Industrial Engineering, South Teheran",
  "Bu Ali Sina University Faculty of Agriculture",
  "Bu Ali Sina University Faculty of Literature and Humanities",
  "Bu Ali Sina University Faculty of Chemistry",
  "Bu Ali Sina University Faculty of Economics and Social Science",
  "Bu Ali Sina University Faculty of Science",
  "Ilam University Faculty of Sciences",
  "Isfahan University of Technology College of Chemistry",
  "Isfahan University of Technology Faculty of Natural Resources",
  "Isfahan University of Technology College of Agriculture",
  "Islamic Azad University of Khorasgan Faculty of Agriculture and Natural Resources",
  "Allameh Tabatabai University Faculty of Economics",
  "Ferdowsi University of Mashhad Faculty of Sciences",
  "Allameh Tabatabai University Faculty of Psychology and Education",
  "Azarbaijan Shahid Madani University Faculty of Humanities",
  "Azarbaijan Shahid Madani University Faculty of Information Technology",
  "Allameh Tabatabai University Faculty of Law and Political Sciences",
  "Allameh Tabatabai University Faculty of Persian Literature and Foreign Languages",
  "Azarbaijan Shahid Madani University Faculty of Basic Sciences",
  "Ferdowski University of Mashhad Faculty of Sports and Physical Education",
  "Allameh Tabatabai University Faculty of Social Sciences and Communication",
  "Azarbaijan Shahid Madani University Faculty of Theology",
  "Al Zahra University Faculty of Sciences",
  "Alzahra University Faculty of Physical Education and Sport Sciences",
  "Shahid Chamran University Faculty of Education and Psychology",
  "Shahid Chamran University Faculty of Science",
  "Shahid Chamran University Faculty of Agriculture",
  "Guilan University Faculty of Agriculture",
  "Imam Khomeini International University Faculty of Science",
  "Imam Khomeini International University Faculty of Literature and Humanities",
  "Shahid Bahonar University Faculty of Agriculture",
  "University of Mazandaran Faculty of Basic Science",
  "University of Mazandaran Faculty of Chemistry",
  "University of Isfahan Faculty of Educational Sciences and Psychology",
  "University of Isfahan Faculty of Foreign Languages",
  "University of Isfahan Faculty of Chemistry",
  "University of Isfahan Faculty of Literature and Humanities",
  "University of Isfahan Faculty of New Sciences and Technology",
  "KN Toosi University of Technology Faculty of Science",
  "University of Kashan Faculty of Foreign Languages and Literatures",
  "University of Kashan Faculty of Chemistry",
  "Semnan University Faculty of Chemistry",
  "Semnan University Faculty of Humanities",
  "Semnan University Faculty of Art",
  "Shahrekord University Faculty of Art",
  "Shahrekord University Faculty of Basic Sciences",
  "Shahrekord University Faculty of Agriculture",
  "ShahreKord University Faculty of Natural Resources and Geosciences",
  "Shahrekord University Faculty of Letters and Humanities",
  "Shiraz University Faculty of Sciences",
  "Payame Noor University Faculty of Basic Sciences",
  "University of Guilan Faculty of Humanities",
  "Shahid Beheshti University Faculty of Earth Sciences",
  "Shahid Beheshti University Faculty of Economics and Political Sciences",
  "Shahid Beheshti University Faculty of Biological Sciences",
  "Shahid Beheshti University Faculty of Chemistry",
  "Shahid Beheshti University Faculty of Physics",
  "Shahid Beheshti University Faculty of Theology and Religious Studies",
  "Tarbiat Modares University Faculty of Biological Sciences",
  "Tarbiat Modares University Faculty of Agriculture",
  "Tarbiat Modares University Faculty of Basic Sciences",
  "Tarbiat Modares University Faculty of Humanities",
  "University of Tabriz Faculty of Agriculture",
  "University of Tabriz Faculty of Persian and Foreign Languages",
  "University of Tehran Faculty of Environment",
  "University of Tehran Faculty of Economics",
  "University of Sistan and Baluchistan Faculty of Agriculture and Natural Resources",
  "University of Sistan and Baluchistan Faculty of Science",
  "University of Sistan and Baluchistan Faculty of Economics",
  "University of Sistan and Baluchistan Faculty of Literature and Humanities",
  "University of Zanjan Faculty of Sciences",
  "Yazd University Faculty of Natural Resources and Desert Studies",
  "Islamic University Shabestar Branch",
  "Shiraz University Faculty of Law and Political Science",
  "Shahid Beheshti University Faculty of Law",
  "Tarbiat Modares University Department of Law",
  "University of Tehran Faculty of Law and Political Science",
  "University of Tehran Faculty of Physical Education and Sport Science",
  "Faculty of Management of the University of Tehran",
  "Faculty of Psychology and Education of the University of Tehran",
  "Amir Al-Momenin University of Military Sciences and Technology",
  "Manjil Naval Base",
  "Faculty of Physical Education and Sport Sciences of the University of Tehran",
  "Faculty of Science of the Salman Farsi University of Kazerun",
  "Farhangian University of Kazerun",
  "Women's Skill National University of Kazerun",
  "Faculty of Architecture",
  "Imam Hossein University",
  "Hamadan University of Technology",
  "Imam Khomeini International University Department of Law",
  "University of Isfahan Department of Law",
  "University of Mazandaran Faculty of Law and Political Sciences",
  "Shiraz University",
  "University of Tabriz",
  "Sharif University of Technology",
  "Islamic Azad University",
  "Iran University of Art",
  "Alzahra University",
  "University of Isfahan",
  "Ferdowsi University of Mashhad",
  "Amirkabir University of Technology",
  "Shahid Beheshti University",
  "Babol Noshirvani University of Technology",
  "University of Tehran",
  "Faculty of Foreign Languages and Literatures of the University of Tehran",
  "AJA University of Command and Staff",
  "Payame Noor University of Kazerun",
  "Imam Khomeini Naval University",
  "Hayati School",
  "Faculty of Literature and Humanities of the University of Tehran",
  "Iran Bethel School",
  "Soureh University",
  "Imam Ali Officers' Academy",
  "EnghelÄb-e EslÄmi Technical College",
  "Faculty of Law and Political Science of the University of Tehran",
  "Faculty of Geography of the University of Tehran",
  "Salman Farsi University of Kazerun",
  "Islamic Azad University of Tabriz",
  "Imam Sadiq University",
  "University of Applied Science and Technology",
  "College of Science of the University of Tehran",
  "Faculty of Economics of the University of Tehran",
  "Khatam al-Anbia Air Defense Academy",
  "Islamic Azad University of Khorasgan Dentistry College",
  "Ferdowsi University of Mashhad Faculty of Agriculture",
  "Ferdowsi University of Mashhad Faculty of Architecture and Urban Planning",
  "Ferdowsi University of Mashhad Faculty of Letters and Humanities",
  "Ferdowsi University of Mashhad Faculty of Natural Resources and Environment",
  "Islamic Azad University Marand Branch",
  "Islamic Azad University of Maragheh",
  "Shahid Chamran University Department of Law",
  "Shahid Chamran University Faculty of Physical Education and Sport Sciences",
  "Lorestan University Faculty of Basic Science",
  "Lorestan University Faculty of Agriculture",
  "Lorestan University Veterinary Faculty",
  "Islamic Azad University of Masjid-i-Solieman",
  "Islamic Azad University of Omidiyeh",
  "Islamic Azad University Meshkin Shahr Branch",
  "Islamic Azad University Naein Branch",
  "Islamic Azad University of Safashahr",
  "Islamic Azad University Sarab",
];
